sudo: false
dist: trusty
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - bower install

before_script:
  - gulp lint
  - polymer lint --rules polymer-2 --input *.html
  - travis_retry xvfb-run -s '-screen 0 1024x768x24' gulp perf:run
  - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || TRAVIS_BRANCH=quick/${TRAVIS_BUILD_ID} xvfb-run -s '-screen 0 1024x768x24' wct)

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
      npm i gemini@^4.0.0 gemini-sauce gemini-polyserve;
      gemini test test/visual;
      gemini test test/visual -c .gemini-ie.yml;
    fi
  - xvfb-run -s '-screen 0 1024x768x24' wct
